params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  caterpillar_3:
    path_to_network_params:/home/davidtseng/pytorch-dense-correspondence/data_volume/pdc/trained_models/tutorials/caterpillar_3/003500.pth
  shark_3:
    path_to_network_params:/home/davidtseng/pytorch-dense-correspondence/data_volume/pdc/trained_models/simulated/shark_3/003500.pth
  shark_depth_3:
    path_to_network_params:/home/davidtseng/pytorch-dense-correspondence/data_volume/pdc/trained_models/simulated/shark_depth_3/005000.pth



dataset: [] # which dataset to use, not used for now

output_dir:/home/davidtseng/pytorch-dense-correspondence/data_volume/pdc/analysis
