autolab-titan-box:
  root:
    path_to_data_directory: '/nfs/diskstation/davidtseng/densenet'

  davidtseng:
    path_to_data_directory: '/nfs/diskstation/davidtseng/densenet'


triton1:
   root:
     path_to_data_directory: '/nfs/diskstation/davidtseng/densenet'
 
   davidtseng:
     path_to_data_directory: '/nfs/diskstation/davidtseng/densenet'
 
