logs_root_path: /home/davidtseng/pytorch-dense-correspondence/data_volume/pdc/logs_proto

single_object_scenes_config_files: []

multi_object_scenes_config_files:
- caterpillar_baymax_starbot_front_only.yaml