logs_root_path: /home/davidtseng/pytorch-dense-correspondence/data_volume/pdc/logs_proto

single_object_scenes_config_files:
- shoe_red_nike.yaml

multi_object_scenes_config_files:
- "/home/davidtseng/pytorch-dense-correspondence/data_volume/pdc/evaluation_labeled_data/shoe_red_nike.yaml"

