logs_root_path: /home/davidtseng/pytorch-dense-correspondence/data_volume/pdc/logs_proto

single_object_scenes_config_files:
- caterpillar_17_scenes.yaml
- baymax.yaml
- gopro_box.yaml
- headphones.yaml
- yellow_robot.yaml
- dramamine.yaml

multi_object_scenes_config_files:
- multi_object.yaml